name: Update deps

on:
  schedule:
    - cron: '0 6 * * 0'
jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Update ca-certs
      run: mkdir -p /etc/ssl/certs/ ; ln -s $NIX_SSL_CERT_FILE /etc/ssl/certs/
    - uses: cachix/cachix-action@v10
      with:
        name: fiksn
        signingKey: '${{ secrets.CACHIX_KEY }}'
    - name: Update deps
      run: nix flake update
    - name: Check
      run: nix flake check
    - name: Push to Cachix
      run: nix build --json | jq -r '.[].outputs | to_entries[].value' | cachix push fiksn
    - name: Push to git
      run: |
        git config --global user.name 'Gregor Pogacnik'
        git config --global user.email '1640719+fiksn@users.noreply.github.com'
        git commit -am "[Automatic] Bump dependencies"
        git push
